# Generated by Django 3.0.3 on 2020-02-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='Country_Name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.AddField(
            model_name='lead',
            name='Vaccine',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
