# Generated by Django 3.0.4 on 2020-03-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200229_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['Country_Name']},
        ),
        migrations.RemoveField(
            model_name='lead',
            name='Vaccine',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='Vaccines',
            field=models.ManyToManyField(to='leads.Vaccine'),
        ),
    ]
