# Generated by Django 3.0.4 on 2020-03-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20200305_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.DecimalField(decimal_places=16, max_digits=22)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='notice',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='detail',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
