# Generated by Django 3.0.4 on 2020-03-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200305_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='makers',
            name='additional_prescribing_authority',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='makers',
            name='address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makers',
            name='certified_travel_consultant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='makers',
            name='hours',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='makers',
            name='injection_certified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='makers',
            name='others',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='makers',
            name='phone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
